# Generated by Django 5.1.4 on 2025-01-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disruption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Maintenance Disruption", "Maintenance Disruption"),
                            ("Material Losses", "Material Losses"),
                            ("Supply Chain Delays", "Supply Chain Delays"),
                            ("Production Related Issues", "Production Related Issues"),
                            ("Quality Related Downtime", "Quality Related Downtime"),
                            ("Line Blockage", "Line Blockage"),
                            ("Line Starvation", "Line Starvation"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("section", models.CharField(max_length=255)),
                ("lotnum", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
