# Generated by Django 5.1.4 on 2025-01-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disruptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disruption",
            name="section",
            field=models.CharField(
                choices=[
                    ("Bodyshop & Metal Finish", "Bodyshop & Metal Finish"),
                    ("Paintshop", "Paintshop"),
                    ("CV Trimline", "CV Trimline"),
                    ("Riveting", "Riveting"),
                    ("N-Series", "N-Series"),
                    ("F-Series", "F-Series"),
                    ("Material Handling", "Material Handling"),
                    ("LCV", "LCV"),
                    ("EOL", "EOL"),
                    ("Other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
