# Generated by Django 5.1.4 on 2024-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_regno"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
